log-messages:
  no-such-book: Book with id = %s  doesn't exist
spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb1
    username: sa
    password: password
    driverClassName: org.h2.Driver
