INSERT INTO BOOK (BOOK_NAME, BOOK_QUANTITY, STATUS) VALUES ('BOOK1', 5, 'REGULAR');
INSERT INTO BOOK (BOOK_NAME, BOOK_QUANTITY, STATUS) VALUES ('BOOK2', 2, 'RARE');
INSERT INTO BOOK (BOOK_NAME, BOOK_QUANTITY, STATUS) VALUES ('BOOK3', 3, 'PUBLIC');